<h1><?php _e('OES Writing Settings', 'oes'); ?></h1>
<p><?php
    printf(__("This is a settings page generated by the OES Core Plugin where you can administrate settings for " .
        "OES features. To administrate WordPress writing settings go %shere%s.", 'oes'),
        '<a href="' . admin_url('options-writing.php') . '">',
        '</a>'
    ); ?>
</p>
<div class="oes-form-wrapper-small"><?php \OES\Admin\Tools\display_tool('writing'); ?></div>
<div class="oes-form-wrapper-small"><?php \OES\Admin\Tools\display_tool('pattern'); ?></div>