<?php

/* Display errors after first h2-header. */
settings_errors();

/* get tool messages */
do_action('admin_notices');

?>
<h1><?php _e('OES Tools', 'oes'); ?></h1>
<p><?php
    printf(__("This is a settings page generated by the OES Core Plugin where you can find " .
        "OES tools. Further WordPress tools are %shere%s.", 'oes'),
        '<a href="' . admin_url('tools.php') . '">',
        '</a>'
    ); ?>
</p>
<div id="poststuff">
    <?php do_meta_boxes('oes-tools', 'normal', ''); ?>
</div>
<script type="text/javascript">
    /* close and expand postboxes */
    jQuery(document).ready(function ($) {
        $('.if-js-closed').removeClass('if-js-closed').addClass('closed');
        postboxes.add_postbox_toggles('oes-settings_page_oes_frontend');
    });
</script>