<div class="oes-page-header-wrapper">
    <div class="oes-page-header">
        <h1><?php _e('OES Writing Settings', 'oes'); ?></h1>
    </div>
    <nav class="oes-tabs-wrapper hide-if-no-js tab-count-7" aria-label="Secondary menu"><?php

        foreach ([
                     'admin-columns' => __('Columns', 'oes'),
                     'admin-container' => __('Container', 'oes'),
                     'admin-info' => __('Info', 'oes')
                 ] as $tab => $label) printf('<a href="%s" class="oes-tab %s">%s</a>',
            admin_url('admin.php?page=oes_settings_writing&tab=' . $tab),
            ((($_GET['tab'] ?? 'admin-columns') == $tab) ? 'active' : ''),
            $label
        );
        ?>
    </nav>
</div>
<div class="oes-page-body"><?php
    if(isset($_GET['tab']) && $_GET['tab'] == 'admin-info'):?>
        <p><?php
            printf(__("This is a settings page generated by the OES Core Plugin where you can administrate settings for " .
                "OES features. To administrate WordPress writing settings go %shere%s.", 'oes'),
                '<a href="' . admin_url('options-writing.php') . '">',
                '</a>'
            ); ?>
        </p><?php
    else: \OES\Admin\Tools\display($_GET['tab'] ?? 'admin-columns');
    endif;
    ?>
</div>