<?php

/* Display errors after first h2-header. */
settings_errors();

/* get tool messages */
do_action('admin_notices');

?>
<h1><?php _e('OES Tools', 'oes'); ?></h1>
<p><?php
    printf(__("This is a settings page generated by the OES Core Plugin where you can find " .
        "OES tools. Further WordPress tools are %shere%s.", 'oes'),
        '<a href="' . admin_url('tools.php') . '">',
        '</a>'
    ); ?>
</p>