<div class="oes-page-header-wrapper">
    <div class="oes-page-header">
        <h1><?php _e('OES Tools', 'oes'); ?></h1>
    </div>
</div>
<div class="oes-page-body">
    <p><?php
        printf(__("This is a settings page generated by the OES Core Plugin where you can find " .
            "OES tools. Further WordPress tools are %shere%s.", 'oes'),
            '<a href="' . admin_url('tools.php') . '">',
            '</a>'
        ); ?>
    </p>
</div>