<h1><?php _e('OES Reading Settings (Theme)', 'oes'); ?></h1>
<p><?php
    printf(__("This is a settings page generated by the OES Core Plugin where you can administrate settings for " .
        "OES features. To administrate WordPress reading settings go %shere%s.", 'oes'),
        '<a href="' . admin_url('options-reading.php') . '">',
        '</a>'
    ); ?>
</p>
<p><?php printf(__('The reading settings administrate the display and behaviour in the frontend (your website as ' .
        'displayed by the selected theme. Learn more about themes in the %sWordPress manual%s). ' .
        'Most of the settings are only intended for the OES theme or a derivative of it and will have no impact ' .
        'on other themes. ', 'oes'),
        '<a href="https://developer.wordpress.org/themes/getting-started/what-is-a-theme/" target="_blank">',
    '</a>');
    _e('A post of a post type (post object) can be displayed on the frontend as a <b>single page</b>, as a search ' .
        'result or as ' .
        'part of an <b>archive</b> listing all posts of a specific post type. For instance, the post type “article” ' .
        'can be displayed in full on one page, can be referred to as the result of a search, or can be listed in an ' .
        'overview of all articles of a reference work.', 'oes');?></p>
<div class="oes-form-wrapper-small"><?php \OES\Admin\Tools\display_tool('reading'); ?></div>
<div class="oes-form-wrapper-small"><?php \OES\Admin\Tools\display_tool('theme-labels'); ?></div>