<?php

namespace OES\Admin\Tools;

if (!defined('ABSPATH')) exit; // Exit if accessed directly


/**
 * Register a tool.
 *
 * @param string $class The tool class name.
 * @param string $name The tool name.
 * @return mixed Returns the registered instance of the Tool class.
 */
function register_tool(string $class, string $name = '', array $args = [])
{
    $instance = empty($args) ? new $class($name) : new $class($name, $args);
    return OES()->admin_tools[$instance->name] = $instance;
}


/**
 * Display a tool.
 *
 * @param string $name The tool name.
 * @return void
 */
function display_tool(string $name): void
{
    $oes = OES();
    if (isset($oes->admin_tools[$name])) $oes->admin_tools[$name]->display_tool();
}


/**
 * Get the link to WordPress Tool Page.
 *
 * @return string The link to WordPress Tool Page.
 */
function get_link_to_wordpress_tools(): string
{
    return '<p>' . sprintf(__("This is a settings page generated by the OES Core Plugin where you can find " .
            "OES tools. Further WordPress tools are %shere%s.", 'oes'),
            '<a href="' . admin_url('tools.php') . '">',
            '</a>'
        ) . '</p>';
}


/**
 * Get the expand button.
 *
 * @return string The html representation of the expand button.
 */
function get_expand_button(): string
{
    return '<div class="oes-config-expand-button-wrapper submit">' .
        '<a href="javascript:void(0);" id="oes-config-expand-all-button" onClick="oesConfigTableToggleRowAll()" class="button button-secondary">' .
        __('Expand All Rows', 'oes') .
        '</a>' .
        '</div>';
}