<?php

namespace OES\Admin\Tools;

use function OES\Rights\user_is_oes_admin;

if (!defined('ABSPATH')) exit; // Exit if accessed directly


/**
 * Include tools.
 *
 * @return void
 */
function include_tools(): void
{
    $path = 'admin/tools/';
    oes_include($path . 'config/functions-config.php');
    foreach ([
                 'admin_columns',
                 'admin_container',
                 'admin_features',
                 'schema',
                 'schema_oes',
                 'schema_oes_single',
                 'schema_oes_archive',
                 'theme_colors',
                 'theme_date',
                 'theme_languages',
                 'theme_logos',
                 'theme_index_pages',
                 'theme_labels_general',
                 'theme_labels_media',
                 'theme_labels_objects',
                 'theme_media',
                 'theme_search',
                 'project'
             ] as $setting)
        oes_include($path . 'config/class-config-' . $setting . '.php');

    oes_include($path . 'class-tool-import.php');
    oes_include($path . 'class-tool-operations.php');
    oes_include($path . 'class-tool-export.php');

    if (function_exists('\OES\Rights\user_is_oes_admin') && user_is_oes_admin()) {
        oes_include($path . 'config/class-config-admin.php');
        oes_include($path . 'class-tool-model.php');
        oes_include($path . 'class-tool-factory.php');
    }
}


/**
 * Register a tool.
 *
 * @param string $class The tool class name.
 * @param string $name The tool name.
 * @return mixed Returns the registered instance of the Tool class.
 */
function register_tool(string $class, string $name = '', array $args = [])
{
    $instance = empty($args) ? new $class($name) : new $class($name, $args);
    return OES()->admin_tools[$instance->name] = $instance;
}


/**
 * Display a tool.
 *
 * @param string $name The tool name.
 * @return void
 */
function display(string $name): void
{
    $oes = OES();
    if (isset($oes->admin_tools[$name])) $oes->admin_tools[$name]->display();
}


/**
 * Display a tool.
 *
 * @oesLegacy Renaming for 2.3
 * @param string $name
 * @return void
 */
function display_tool(string $name): void
{
    display($name);
}


/**
 * Get the link to WordPress Tool Page.
 *
 * @return string The link to WordPress Tool Page.
 */
function get_link_to_wordpress_tools(): string
{
    return '<p>' . sprintf(__("This is a settings page generated by the OES Core Plugin where you can find " .
            "OES tools. Further WordPress tools are %shere%s.", 'oes'),
            '<a href="' . admin_url('tools.php') . '">',
            '</a>'
        ) . '</p>';
}


/**
 * Get the expand button.
 *
 * @return string The html representation of the expand button.
 */
function get_expand_button(): string
{
    return '<div class="submit" style="float:right;">' .
        '<a href="javascript:void(0);" id="oes-config-expand-all-button" onClick="oesLabel.toggleAll()" ' .
        'class="button button-secondary">' .
        __('Expand All Rows', 'oes') .
        '</a>' .
        '</div>';
}