<?php
/*
 * This file is part of OES, the Open Encyclopedia System.
 *
 * Copyright (C) 2020 Freie Universität Berlin, Center für Digitale Systeme an der Universitätsbibliothek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
?>

<?php

class Oes_Mini_Searchquery_Renderer extends Oes_Mini_Renderer
{

    public function __construct(string $base = 'searchquery@renderer')
    {
        parent::__construct($base);
    }

    function init($params = [])
    {
        parent::init($params); // TODO: Change the autogenerated stub
    }


    function area_main()
    {

        ?>
        <div area-id="listing"></div>
        <div area-id="paging"></div>
        <div area-id="char_class_filter"></div>
        <div area-id="filter_options"></div>
        <?php

    }

    function area_listing()
    {

        ?><h3>Listing</h3><?php
        $this->depends_on_area("main");

    }

    function area_filter_options()
    {
        ?><h3>Filter Options</h3><?php

        $this->depends_on_area("main");

    }

    function area_char_class_filter()
    {

        ?><h3>Char Class Filter</h3><?php

        $this->depends_on_area("main");

    }

    function area_paging()
    {

        ?><h3>Paging</h3><?php

        $this->depends_on_area("main");

    }

}

