<?php

/**
 * Formulas can be used to transform data according to a mapping pattern.
 * @oesDevelopment Make formula available through shortcode.
 * @oesDevelopment Add 'overwrite' option.
 */

namespace OES\Formula;

if (!defined('ABSPATH')) exit; // Exit if accessed directly

use function OES\Versioning\get_parent_id;


/**
 * Calculate post arguments from formula (pattern).
 *
 * @param mixed $postID The considered post ID.
 * @return void
 */
function calculate_post_args_from_formula($postID): void
{
    $currentPostType = get_post_type($postID);
    $args = [];

    $postData = OES()->post_types[$currentPostType] ?? [];

    $patternTitle = $postData['pattern_title'] ?? null;

    if ($patternTitle) {
        $newTitle = calculate_post_title_from_formula($patternTitle, $postID);

        if (!empty($newTitle)) {
            $args['post_title'] = $newTitle;
        }
    }

    $patternName = $postData['pattern_name'] ?? null;

    if ($patternName) {
        $newName = calculate_post_title_from_formula($patternName, $postID);

        if (!empty($newName)) {
            $args['post_name'] = $newName;
        }
    }

    if ($args) {
        wp_update_post(array_merge(['ID' => $postID], $args));
    }
}

/**
 * Calculate post title from formula (pattern).
 *
 * @param array $pattern The title pattern.
 * @param mixed $postID The considered post ID.
 * @param bool $overwrite Indicating if title is to be overwritten even if title is not empty.
 * @param string $separator The separator between parts.
 * @return string Return the calculated post title or empty.
 */
function calculate_post_title_from_formula(
    array  $pattern,
           $postID,
    bool   $overwrite = false,
    string $separator = ''): string
{
    $parts = $pattern['parts'] ?? false;

    if(!$parts){
        return '';
    }

    $currentTitle = get_the_title($postID);

    if(!$overwrite && !empty($currentTitle)){
        return '';
    }

    return calculate_value($parts, $postID, $separator);
}

/**
 * Calculate post name from formula (pattern).
 *
 * @param array $pattern The name (slug) pattern.
 * @param mixed $postID The considered post ID.
 * @param bool $overwrite Indicating if title is to be overwritten even if title is not empty.
 * @param string $separator The separator between parts.
 * @return string Return the calculated post name or empty.
 */
function calculate_post_name_from_formula(
    array  $pattern,
           $postID,
    bool   $overwrite = false,
    string $separator = ''): string
{
    $parts = $pattern['parts'] ?? false;

    if(!$parts){
        return '';
    }

    $name = get_post($postID)->post_name;
    $isAutoGeneratedSlug = ((string)$postID === $name);

    if (!$overwrite && !empty($name) && !$isAutoGeneratedSlug) {
        return '';
    }

    $newName = calculate_value($parts, $postID, $separator);

    if ($newName === $name) {
        return '';
    }

    return $newName;
}

/**
 * Calculate field value from formula (pattern).
 *
 * @param mixed $value The field value.
 * @param int|string $postID The post ID where the value is saved.
 * @param array $field The field array containing all settings.
 * @param bool $overwrite Indicating if title is to be overwritten even if title is not empty.
 * @return mixed
 */
function calculate_field_value_from_formula($value, $postID, array $field, bool $overwrite = false): mixed
{
    if (!$postID) {
        return $value;
    }

    $pattern = OES()->post_types[get_post_type($postID)]['field_options'][$field['key']]['pattern'] ?? [];

    if(!$pattern) {
        return $value;
    }

    if($field['readonly'] ?? false) {
        $overwrite = true;
    }

    if(!empty($value) && !$overwrite && ($value !== 'generate')){
        return $value;
    }

    $newValue = calculate_value($pattern, $postID);

    if($newValue) {
        return $newValue;
    }

    return $value;
}

/**
 * Create new string from array parameters.
 *
 * @param array $parts The parts containing field key and additional information.
 * @param int $postID The post ID.
 * @param string $separator The separator between parts.
 * @param bool $sort Whether to sort relationship/post_object display values.
 * @return string Return the parts as string.
 *
 * @oesDevelopment More options, add parent fields, make link optional, return $url instead of anchor...
 */
function calculate_value(array $parts, int $postID, string $separator = '', bool $sort = false): string
{
    $stringParts = [];

    foreach ($parts as $part) {
        $part = normalize_legacy_part_keys($part);

        $prefix = $part['prefix'] ?? '';
        $suffix = $part['suffix'] ?? '';
        $fieldKey = $part['field_key'] ?? false;

        if ($fieldKey) {
            $value = resolve_part_value($part, $fieldKey, $postID, $sort);

            if (!empty($value)) {
                $stringParts[] = $prefix . $value . $suffix;
            } elseif ($part['required'] ?? false) {
                $stringParts[] = $part['string_value'] ?? 'Value Missing (' . $fieldKey . ')';
            }
        } elseif ($string = $part['string_value'] ?? false) {
            $stringParts[] = $prefix . $string . $suffix;
        }
    }

    return empty($stringParts) ? '' : implode($separator, $stringParts);
}

/**
 * @oesLegacy rename old pattern parameter keys to current ones (in place, non-destructive to caller).
 */
function normalize_legacy_part_keys(array $part): array
{
    if (isset($part['default']) && !isset($part['string_value'])) {
        $part['string_value'] = $part['default'];
    }
    if (isset($part['key']) && !isset($part['field_key'])) {
        $part['field_key'] = $part['key'];
    }
    if (isset($part['fallback_field_key']) && !isset($part['fallback'])) {
        $part['fallback'] = $part['fallback_field_key'];
    }
    return $part;
}

/**
 * Strip a 'parent__' prefix from a field key and resolve the post ID it applies to.
 * Returns [resolvedFieldKey, resolvedPostID].
 */
function resolve_parent_prefixed_key(string $fieldKey, int $postID): array
{
    if (str_starts_with($fieldKey, 'parent__')) {
        return [substr($fieldKey, 8), get_parent_id($postID)];
    }
    return [$fieldKey, $postID];
}

/**
 * Resolve the raw field key/value/object for a part, including fallback-field
 * and 'parent__' handling for both the primary and fallback key.
 */
function resolve_part_value(array $part, string $fieldKey, int $postID, bool $sort)
{
    if ($fieldKey === 'none' || $fieldKey === 'no_field_key') {
        return $part['string_value'] ?? '';
    }

    $args = ['list-class' => 'oes-field-value-list'];
    if(!$sort){
        $args['sort'] = false;
    }

    $fieldValue = oes_get_field_display_value($fieldKey, $postID, $args);

    if (empty($fieldValue) && !empty($part['fallback'])) {
        $fieldValue = oes_get_field_display_value($part['fallback'], $postID, $args);
    }

    return $fieldValue;
}
